import { Sidebar } from "@/components/portfolio";
import Navbar from "@/components/portfolio/Navbar";
import Icon from "@/components/utils/Icon";
import type { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by gofolio.in",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="bg-crimson-50 min-h-screen">
      <div className="max-w-screen-xl mx-auto flex items-start justify-between gap-6 pt-40">
        <Sidebar />
        <div className="flex flex-col gap-6 w-full">
          <div className="flex items-center justify-end w-full">
            <Navbar />
          </div>
          {children}
        </div>
      </div>
    </main>
  );
}
