import Navbar from "@/components/site/Navbar";
import Icon from "@/components/utils/Icon";
import type { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by gofolio.in",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="bg-crimson-50 min-h-screen">
      <Navbar />
      <div className="max-w-screen-2xl mx-auto">{children}</div>
    </main>
  );
}
